"""tester/shim.py — the tester's always-on front on the heartbeat.

The tester runs proofs and attests verdicts. Its shim is thin: wake a TesterDevice on
first delivery, expose its page. No constructor-injected state — the device stands alone.
"""

from __future__ import annotations

from cairn.tools.base.shim import BaseShim


class TesterShim(BaseShim):

    def __init__(self, bus=None) -> None:
        super().__init__(bus=bus)

    @property
    def device_id(self) -> str:
        return "tester"

    def _start_device(self):
        from cairn.devices.tester.device import TesterDevice
        return TesterDevice()

    def deliver(self, envelope: dict):
        """A REPLY IS TAKEN AND THROWN AWAY HERE (ticket cff5a197b3c4). Akien, 2026-09-23:
        "All mail generated by tester has to be managed by the testers shim. Period." — and
        it is of no use once the testing is complete. So a reply is printed (a refused seal
        is never stored silently, Law 7) and kept nowhere; the caller receipts it. Keeping
        one is a named choice made here, never the default."""
        if not envelope.get("reply_to"):
            return super().deliver(envelope)
        body = envelope.get("body") or {}
        for refused in body.get("refused") or []:
            print(f"  refused: {refused.get('ticket', '?')} — {refused.get('reason', '')}")
        for ticket in body.get("crossed") or []:
            print(f"  crossed: {ticket}")
        self.emit("reply_disposed", pointer=envelope.get("id"),
                  values={"reply_to": envelope["reply_to"],
                          "refused": len(body.get("refused") or []),
                          "crossed": len(body.get("crossed") or [])})
        return {"disposed": True, "reply_to": envelope["reply_to"]}
