"""PROOF for ticket cff5a197b3c4: the tester takes its reply.

Every verb handler's dict goes back to its sender as a personal "<verb> reply"
(cairn/tools/base/shim.py deliver). The tester announces each seal to codemother with a
post and then exits, and its own shim was never wired in that process. So every "sealed
reply" landed in the store undelivered, forever. Measured 2026-10-02: 633 standing, all
codemother -> tester. Akien, 2026-09-23 (open-9d1bb9b4d708): "All mail generated by tester
has to be managed by the testers shim. Period." Such mail is of no use once testing is done.

One tooth per numbered falsifier clause this file declares (clause 4, press_office, is the
bus's: cairn/devices/cairn/machines/bus/proofs/test_folder_mail_lands_late.py):

  1. THE TESTER CLEARS ITS OWN REPLY: under a scratch bus, a tester shim and a stub
     codemother shim are wired. A seal exchange then leaves undelivered(to='tester')
     empty, and the receipt is by 'tester'. The proof does no clearing. The CLI also
     reaches 'tester', so the live exchange wires the same shim.
  2. REFUSED IS PRINTED: a reply carrying refused[] prints one line per refused ticket,
     naming the reason, at the exchange.
  3. DISCARD BY DEFAULT: the exchange grows no file under the tester's data_recorder
     inbound.
  5. THE STANDING PILE DRAINS BY THE SHIM: replies to 'tester' are stored while no tester
     shim is wired. Wiring the shim disposes all of them, and undelivered(to='tester')
     reads 0. And on the LIVE bus, undelivered(to='tester') reads 0: once the one-time
     drain has run, every later seal run is taken at its own exchange (633 stood at HEAD).

Requires Postgres; every bus rides BusDevice.scratch and drops at close.

    python3 cairn/devices/tester/proofs/test_the_tester_takes_its_reply.py
"""

from __future__ import annotations

import contextlib
import io
import sys
from datetime import datetime, timezone
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[4]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from cairn.tools.base.shim import BaseShim, ONLINE  # noqa: E402
from cairn.tools.base.device import BaseDevice  # noqa: E402
from cairn.devices.cairn.machines.bus.bus import BusDevice  # noqa: E402
from cairn.devices.cairn.machines.bus.shim import BusShim  # noqa: E402
from cairn.tools.bus_client.roster import DeviceRoster  # noqa: E402
from cairn.devices.db_domain.tools.client import store  # noqa: E402
from cairn.devices.tester.shim import TesterShim  # noqa: E402

PROVES = {"cff5a197b3c4": {
    "1": "the_tester_clears_its_own_reply",
    "2": "a_refused_seal_is_printed_at_the_exchange",
    "3": "the_exchange_keeps_nothing_by_default",
    "5": "the_standing_pile_is_drained_by_the_shim",
}}

_SCRATCH = contextlib.ExitStack()
NOW = datetime(2026, 10, 2, 12, 0, tzinfo=timezone.utc)
_INBOUND = (Path.home() / ".cairn" / "devices" / "tester" / "0" / "tools"
            / "data_recorder" / "inbound")
_REFUSAL = "testing-cff5a197b3c4 the harbor refused this boat"
PASS = 0
FAIL = 0


class StubCodemother(BaseDevice):
    """Answers 'sealed' the way codemother's shim does: crossed[] and refused[]."""

    def intention(self) -> dict:
        return {"what": "testing-cff5a197b3c4 stub codemother"}

    def state(self) -> dict:
        return {"at": "running"}

    def settings(self) -> dict:
        return {}

    def declared_verbs(self) -> dict:
        return {"sealed": lambda envelope: {
            "accepted": True, "verb": "sealed",
            "crossed": ["testing-crossed-0001"],
            "refused": [{"ticket": "testing-refused-0001", "reason": _REFUSAL}],
            "awaiting_hollow": []}}


class _Shim(BaseShim):
    def __init__(self, device_id, device, bus) -> None:
        super().__init__(bus=bus)
        self._device_id = device_id
        self._device = device
        self._presence = ONLINE

    @property
    def device_id(self) -> str:
        return self._device_id

    def _start_device(self):
        return self._device


def _rig(*, with_tester: bool = True):
    bus = _SCRATCH.enter_context(BusDevice.scratch("bus_ttr"))
    loop = DeviceRoster(bus)
    loop.hold(BusShim(bus, loop))
    loop.hold(_Shim("codemother", StubCodemother(), bus))
    if with_tester:
        loop.hold(TesterShim(bus=bus))
    loop.pulse(NOW)
    return bus, loop


def _seal_exchange(bus):
    out = io.StringIO()
    with contextlib.redirect_stdout(out):
        sent = bus.post(sender="tester", to="codemother", channel="personal", verb="sealed",
                        why="testing-cff5a197b3c4 a green seal landed",
                        body={"proof": "testing-cff5a197b3c4/proofs/test_x.py",
                              "verdict": "green"})
        bus.flush()
    return sent, out.getvalue()


def _inbound_bytes() -> dict:
    if not _INBOUND.is_dir():
        return {}
    return {p.name: p.stat().st_size for p in _INBOUND.rglob("*") if p.is_file()}


def the_tester_clears_its_own_reply():
    bus, _ = _rig()
    sent, _ = _seal_exchange(bus)
    left = bus.undelivered(to="tester", limit=1000)
    assert not left, f"{len(left)} envelope(s) still stand undelivered to the tester: {left}"
    replies = bus.read(to="tester", channel="personal", reply_to=sent["id"])
    assert replies, "codemother's stub never replied — the exchange did not happen"
    rows = store.read(bus.delivery_table, where="envelope = %s",
                      params=(replies[0]["id"],))
    assert rows and all(r.get("by") == "tester" for r in rows), (
        f"the reply's receipt is not the tester's own: {rows}")
    cli = (_REPO_ROOT / "cairn" / "devices" / "tester" / "cli.py").read_text()
    assert 'reach("codemother", "harbor_master", "tester")' in cli, (
        "the seal CLI does not reach 'tester', so its own shim is unwired at the live exchange")


def a_refused_seal_is_printed_at_the_exchange():
    bus, _ = _rig()
    _, printed = _seal_exchange(bus)
    assert "refused: testing-refused-0001" in printed and _REFUSAL in printed, (
        f"the refused seal was not printed at the exchange; stdout was {printed!r}")
    assert "crossed: testing-crossed-0001" in printed, (
        f"the crossed seal was not printed at the exchange; stdout was {printed!r}")


def the_exchange_keeps_nothing_by_default():
    before = _inbound_bytes()
    bus, _ = _rig()
    _seal_exchange(bus)
    after = _inbound_bytes()
    assert after == before, f"the tester's inbound grew: {before} -> {after}"


def the_standing_pile_is_drained_by_the_shim():
    bus, loop = _rig(with_tester=False)
    for n in range(3):
        bus.post(sender="codemother", to="tester", channel="personal",
                 why="sealed reply", body={"crossed": [], "refused": []},
                 reply_to=f"testing-cff5a197b3c4-standing-{n}")
    bus.flush()
    assert len(bus.undelivered(to="tester", limit=1000)) == 3, "the fixture pile did not stand"
    with contextlib.redirect_stdout(io.StringIO()):
        loop.hold(TesterShim(bus=bus))
        loop.pulse(NOW)
        bus.flush()
    left = bus.undelivered(to="tester", limit=1000)
    assert not left, f"the tester shim left {len(left)} of 3 standing replies undelivered"
    live = BusDevice().undelivered(to="tester", limit=10000)
    assert not live, f"{len(live)} envelope(s) stand undelivered to the tester on the live bus"


TEETH = [the_tester_clears_its_own_reply,
         a_refused_seal_is_printed_at_the_exchange,
         the_exchange_keeps_nothing_by_default,
         the_standing_pile_is_drained_by_the_shim]


def _tooth(fn):
    global PASS, FAIL
    try:
        fn()
    except Exception as exc:  # noqa: BLE001 — a proof reports, never hides
        FAIL += 1
        print(f"  RED   {fn.__name__}: {type(exc).__name__}: {exc}")
    else:
        PASS += 1
        print(f"  green {fn.__name__}")


if __name__ == "__main__":
    try:
        for fn in TEETH:
            _tooth(fn)
    finally:
        _SCRATCH.close()
    print(f"{PASS} passed, {FAIL} failed out of {PASS + FAIL}")
    sys.exit(1 if FAIL else 0)
